export const VERSION = "1.0.0";

export const DEFAULT_EXCLUDED_DIRS = [
  ".git",
  "node_modules",
  ".next",
  ".nuxt",
  "dist",
  "build",
  "coverage",
  ".venv",
  "venv",
  "__pycache__",
  ".cache",
  ".idea",
  ".vscode",
  ".tox",
  ".mypy_cache",
  ".pytest_cache",
  "eggs",
  ".eggs",
  "tmp",
  ".tmp",
];

export const DEFAULT_OUTPUT = "README.md";
export const DEFAULT_MANIFEST = "PROJECT-SNAPSHOT.json";

export const TEXT_EXTENSIONS = new Set([
  ".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
  ".json", ".jsonl", ".json5",
  ".yaml", ".yml",
  ".toml",
  ".xml", ".html", ".htm", ".xhtml",
  ".css", ".scss", ".sass", ".less",
  ".md", ".mdx", ".rst", ".txt",
  ".sql",
  ".sh", ".bash", ".zsh", ".fish",
  ".ps1", ".psm1", ".psd1",
  ".bat", ".cmd",
  ".rs", ".go", ".java", ".kt", ".kts",
  ".c", ".h", ".cpp", ".hpp", ".cxx", ".cc",
  ".cs",
  ".php",
  ".rb",
  ".vue", ".svelte",
  ".lua",
  ".dart",
  ".swift",
  ".r", ".R",
  ".pl", ".pm",
  ".tcl",
  ".ini", ".cfg", ".conf",
  ".env", ".env.local", ".env.production",
  ".dockerfile", ".dockerignore",
  ".gitignore", ".gitattributes",
  ".editorconfig",
  ".prettierrc", ".eslintrc",
  ".babelrc",
  "Makefile", "Dockerfile", "Jenkinsfile",
  "CMakeLists.txt",
  "setup.py", "setup.cfg", "pyproject.toml",
  "Gemfile", "Rakefile",
  "Gruntfile.js", "gulpfile.js",
  "webpack.config.js", "vite.config.js", "rollup.config.js",
]);

export const BINARY_EXTENSIONS = new Set([
  ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg", ".webp",
  ".mp3", ".mp4", ".avi", ".mov", ".wmv", ".flv", ".webm", ".mkv",
  ".wav", ".flac", ".aac", ".ogg", ".wma",
  ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
  ".exe", ".dll", ".so", ".dylib", ".bin",
  ".ttf", ".otf", ".woff", ".woff2", ".eot",
  ".sqlite", ".db", ".sqlite3",
  ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
  ".pyc", ".pyo", ".class",
  ".o", ".obj", ".lib", ".a",
  ".iso", ".img", ".dmg",
]);

export const LANGUAGE_MAP: Record<string, string> = {
  ".py": "Python",
  ".js": "JavaScript",
  ".mjs": "JavaScript",
  ".cjs": "JavaScript",
  ".jsx": "React JavaScript",
  ".ts": "TypeScript",
  ".tsx": "React TypeScript",
  ".java": "Java",
  ".c": "C",
  ".h": "C Header",
  ".cpp": "C++",
  ".hpp": "C++ Header",
  ".cxx": "C++",
  ".cc": "C++",
  ".cs": "C#",
  ".go": "Go",
  ".rs": "Rust",
  ".rb": "Ruby",
  ".php": "PHP",
  ".swift": "Swift",
  ".kt": "Kotlin",
  ".kts": "Kotlin Script",
  ".dart": "Dart",
  ".lua": "Lua",
  ".sh": "Shell",
  ".bash": "Bash",
  ".zsh": "Zsh",
  ".fish": "Fish",
  ".ps1": "PowerShell",
  ".psm1": "PowerShell Module",
  ".bat": "Batch",
  ".cmd": "Batch",
  ".html": "HTML",
  ".htm": "HTML",
  ".xhtml": "XHTML",
  ".css": "CSS",
  ".scss": "SCSS",
  ".sass": "Sass",
  ".less": "Less",
  ".vue": "Vue",
  ".svelte": "Svelte",
  ".json": "JSON",
  ".jsonl": "JSON Lines",
  ".yaml": "YAML",
  ".yml": "YAML",
  ".toml": "TOML",
  ".xml": "XML",
  ".sql": "SQL",
  ".md": "Markdown",
  ".mdx": "MDX",
  ".rst": "reStructuredText",
  ".txt": "Text",
  ".r": "R",
  ".R": "R",
  ".pl": "Perl",
  ".pm": "Perl Module",
  ".tcl": "Tcl",
  ".ini": "INI",
  ".cfg": "Config",
  ".conf": "Config",
  ".dockerfile": "Dockerfile",
  ".dockerignore": "Docker Ignore",
  ".gitignore": "Git Ignore",
  ".gitattributes": "Git Attributes",
  ".editorconfig": "EditorConfig",
};

export const SECRET_PATTERNS = [
  /-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----/g,
  /ghp_[A-Za-z0-9]{36}/g,
  /github_pat_[A-Za-z0-9_]{82}/g,
  /AKIA[0-9A-Z]{16}/g,
  /AIza[0-9A-Za-z\-_]{35}/g,
  /sk-[A-Za-z0-9]{48}/g,
  /sk_live_[A-Za-z0-9]{24,}/g,
  /pk_live_[A-Za-z0-9]{24,}/g,
  /SQ0csp-[A-Za-z0-9\-_]{43}/g,
  /xox[baprs]-[A-Za-z0-9\-]+/g,
  /password\s*[:=]\s*['"][^'"]+['"]/gi,
  /secret\s*[:=]\s*['"][^'"]+['"]/gi,
  /api[_-]?key\s*[:=]\s*['"][^'"]+['"]/gi,
  /access[_-]?token\s*[:=]\s*['"][^'"]+['"]/gi,
];

export const SECRET_FILENAMES = new Set([
  ".env",
  ".env.local",
  ".env.development",
  ".env.production",
  ".env.staging",
  ".env.test",
  "credentials.json",
  "service-account.json",
  "serviceAccountKey.json",
  ".npmrc",
  ".pypirc",
  ".netrc",
  ".htpasswd",
  "id_rsa",
  "id_ed25519",
  "id_dsa",
  "id_ecdsa",
]);

export const SAMPLE_PROJECT_SNAPSHOT_REPO = {
  name: "project-snapshot",
  gitInfo: {
    isRepository: true,
    branch: "main",
    commit: "d4e28f731a5c6020c2a8f334a1b2c3d4e5f67890",
    shortCommit: "d4e28f7",
    origin: "https://github.com/mohammadhossein-asadi/project-snapshot.git",
    modifiedFiles: [],
    untrackedFiles: [],
  },
  files: [
    {
      path: "project_snapshot.py",
      name: "project_snapshot.py",
      content: `#!/usr/bin/env python3\n"""Project Snapshot — Cross-platform zero-dependency project documentation and codebase snapshot generator."""\nimport sys\nfrom pathlib import Path\nsys.path.insert(0, str(Path(__file__).parent / "src"))\nfrom snapshot.cli import main\n\nif __name__ == "__main__":\n    sys.exit(main())\n`,
    },
    {
      path: "src/snapshot/__init__.py",
      name: "__init__.py",
      content: `"""Project Snapshot — Zero-dependency codebase snapshot generator."""\n__version__ = "1.0.0"\n`,
    },
    {
      path: "src/snapshot/cli.py",
      name: "cli.py",
      content: `import argparse\nimport sys\nfrom pathlib import Path\nfrom .constants import DEFAULT_OUTPUT, DEFAULT_MANIFEST, DEFAULT_EXCLUDED_DIRS\nfrom .scanner import scan_project\nfrom .output import write_output\n\ndef main(argv=None):\n    parser = argparse.ArgumentParser(prog="project-snapshot")\n    parser.add_argument("path", nargs="?", default=".")\n    args = parser.parse_args(argv)\n    print(f"Scanning project: {args.path}")\n    return 0\n`,
    },
    {
      path: "src/snapshot/constants.py",
      name: "constants.py",
      content: `VERSION = "1.0.0"\nDEFAULT_EXCLUDED_DIRS = {".git", "node_modules", "dist", ".venv"}\nDEFAULT_OUTPUT = "README.md"\nDEFAULT_MANIFEST = "PROJECT-SNAPSHOT.json"\n`,
    },
    {
      path: "src/snapshot/scanner.py",
      name: "scanner.py",
      content: `import os\nfrom pathlib import Path\nfrom .hashing import compute_sha256\nfrom .secrets import scan_for_secrets\n\ndef scan_project(project_root, max_size=10*1024*1024):\n    # Core directory traversal & metadata collection\n    return {"files": [], "stats": {}}\n`,
    },
    {
      path: "src/snapshot/secrets.py",
      name: "secrets.py",
      content: `import re\nfrom .constants import SECRET_PATTERNS\n\ndef is_secret_file(path):\n    return path.name.startswith(".env")\n\ndef scan_for_secrets(file_path):\n    return {"is_secret_file": is_secret_file(file_path), "has_secrets": False}\n`,
    },
    {
      path: "src/snapshot/tree.py",
      name: "tree.py",
      content: `def build_tree(root, prefix="", excluded_dirs=None):\n    # Deterministic directory tree generator\n    return ["."]\n`,
    },
    {
      path: "src/snapshot/output.py",
      name: "output.py",
      content: `import json\nfrom datetime import datetime, timezone\n\ndef write_output(scan_result, output_path, manifest_path):\n    # Writes Markdown snapshot & JSON manifest\n    pass\n`,
    },
    {
      path: "tests/test_scanner.py",
      name: "test_scanner.py",
      content: `def test_scanner_basic():\n    assert True\n`,
    },
    {
      path: ".env.example",
      name: ".env.example",
      content: `API_KEY=your_key_here\nDATABASE_URL=postgres://user:pass@localhost:5432/db\n`,
    },
    {
      path: "LICENSE",
      name: "LICENSE",
      content: `MIT License\n\nCopyright (c) 2026 Mohammad Hossein Asadi\n\nPermission is hereby granted, free of charge...`,
    },
  ],
};
