import { VERSION, DEFAULT_EXCLUDED_DIRS } from './constants';
import { ScanResult, SnapshotOptions } from '../types';
import { generateTreeString } from './tree';

export function formatJsonManifest(scanResult: ScanResult): Record<string, unknown> {
  return {
    tool: {
      name: "project-snapshot",
      version: VERSION,
    },
    timestamp: scanResult.timestamp,
    environment: {
      platform: typeof navigator !== 'undefined' ? navigator.userAgent : "Web Environment",
      engine: "JavaScript/TypeScript Web Engine",
      browser: typeof navigator !== 'undefined' ? navigator.appName : "Unknown",
    },
    project: {
      name: scanResult.projectName,
      root: scanResult.projectName,
    },
    git: scanResult.gitInfo,
    statistics: scanResult.stats,
    files: scanResult.files.map(f => {
      // Exclude full text content from manifest as per specification
      // eslint-disable-next-line @typescript-eslint/no-unused-vars
      const { content, ...rest } = f;
      return rest;
    }),
    errors: scanResult.errors,
  };
}

export function formatMarkdown(
  scanResult: ScanResult,
  options: Partial<SnapshotOptions> = {}
): string {
  const stats = scanResult.stats;
  const files = scanResult.files;
  const gitInfo = scanResult.gitInfo;
  const includeDefaultHeavy = options.includeDefaultHeavy ?? false;

  const sections: string[] = [];

  // Header
  sections.push(`# Project Snapshot: \`${scanResult.projectName}\``);
  sections.push("");
  sections.push(`> Generated by **Project Snapshot v${VERSION}** on ${scanResult.timestamp}`);
  sections.push("");

  // Environment
  sections.push("## Environment");
  sections.push("");
  sections.push(`- **Platform:** Web / Node.js Engine`);
  sections.push(`- **Client:** ${typeof navigator !== 'undefined' ? navigator.userAgent : "Node.js"}`);
  sections.push("");

  // Git Information
  sections.push("## Git Information");
  sections.push("");
  if (gitInfo.isRepository) {
    sections.push(`- **Repository:** Yes`);
    sections.push(`- **Branch:** \`${gitInfo.branch || "main"}\``);
    sections.push(`- **Commit:** \`${gitInfo.shortCommit || gitInfo.commit?.substring(0, 7) || "unknown"}\``);
    if (gitInfo.origin) {
      sections.push(`- **Origin:** \`${gitInfo.origin}\``);
    }
    if (gitInfo.modifiedFiles && gitInfo.modifiedFiles.length > 0) {
      sections.push(`- **Modified files:** ${gitInfo.modifiedFiles.length}`);
    }
    if (gitInfo.untrackedFiles && gitInfo.untrackedFiles.length > 0) {
      sections.push(`- **Untracked files:** ${gitInfo.untrackedFiles.length}`);
    }
  } else {
    sections.push(`- **Repository:** No (not a Git repository)`);
  }
  sections.push("");

  // Excluded Directories
  if (!includeDefaultHeavy) {
    sections.push("## Excluded Directories");
    sections.push("");
    sections.push(
      "The following directories are excluded by default to avoid scanning " +
      "generated/dependency content. Use `--include-default-heavy` to include them."
    );
    sections.push("");
    for (const d of [...DEFAULT_EXCLUDED_DIRS].sort()) {
      sections.push(`- \`${d}\``);
    }
    sections.push("");
  }

  // Project Statistics
  sections.push("## Project Statistics");
  sections.push("");
  sections.push("| Metric | Value |");
  sections.push("|--------|-------|");
  sections.push(`| Total files | ${stats.totalFiles} |`);
  sections.push(`| Total directories | ${stats.totalDirectories} |`);
  sections.push(`| Total size | ${stats.totalSizeHuman} |`);
  sections.push(`| Text files | ${stats.textFiles} |`);
  sections.push(`| Binary files | ${stats.binaryFiles} |`);
  sections.push(`| Symlinks | ${stats.symlinks} |`);
  sections.push(`| Secret detections | ${stats.secretDetections} |`);
  sections.push("");

  // Languages
  if (Object.keys(stats.languages).length > 0) {
    sections.push("## Languages");
    sections.push("");
    sections.push("| Language | Files |");
    sections.push("|----------|-------|");
    for (const [lang, count] of Object.entries(stats.languages)) {
      sections.push(`| ${lang} | ${count} |`);
    }
    sections.push("");
  }

  // File Extensions
  if (Object.keys(stats.extensions).length > 0) {
    sections.push("## File Extensions");
    sections.push("");
    sections.push("| Extension | Count |");
    sections.push("|-----------|-------|");
    for (const [ext, count] of Object.entries(stats.extensions)) {
      sections.push(`| \`${ext}\` | ${count} |`);
    }
    sections.push("");
  }

  // Project Tree
  const treeStr = generateTreeString(
    files.map(f => ({ path: f.path, isDirectory: f.isDirectory })),
    includeDefaultHeavy ? new Set() : new Set(DEFAULT_EXCLUDED_DIRS)
  );
  sections.push("## Project Tree");
  sections.push("");
  sections.push("```text");
  sections.push(treeStr);
  sections.push("```");
  sections.push("");

  // Largest Files
  if (stats.largestFiles && stats.largestFiles.length > 0) {
    sections.push("## Largest Files");
    sections.push("");
    sections.push("| Size | Path |");
    sections.push("|------|------|");
    for (const lf of stats.largestFiles.slice(0, 15)) {
      const sizeStr = formatBytes(lf.size);
      sections.push(`| ${sizeStr} | \`${lf.path}\` |`);
    }
    sections.push("");
  }

  // File Contents
  sections.push("## File Contents");
  sections.push("");

  for (const f of files) {
    if (f.isDirectory) continue;

    sections.push(`### \`${f.path}\``);
    sections.push("");

    if (f.isSymlink) {
      sections.push(`- **Type:** Symlink`);
      sections.push(`- **Target:** \`${f.symlinkTarget || "unknown"}\``);
      sections.push("");
      continue;
    }

    sections.push(`- **Size:** ${f.sizeHuman}`);
    sections.push(`- **SHA-256:** \`${f.sha256}\``);
    if (f.modified) {
      sections.push(`- **Modified:** ${f.modified}`);
    }
    if (f.permissions) {
      sections.push(`- **Permissions:** ${f.permissions}`);
    }
    if (f.language && f.language !== "Unknown") {
      sections.push(`- **Language:** ${f.language}`);
    }
    if (f.mimeType) {
      sections.push(`- **MIME:** ${f.mimeType}`);
    }

    if (f.secretInfo.hasSecrets) {
      sections.push("");
      if (f.secretInfo.isSecretFile) {
        sections.push("> 🔒 **Potential secret detected.** Content intentionally not embedded.");
        sections.push(">");
        sections.push("> This file appears to contain sensitive information (e.g., API keys, credentials, private keys).");
        sections.push("> Only metadata is included in this snapshot for security reasons.");
      } else if (f.secretInfo.contentSecrets.length > 0) {
        sections.push(
          `> 🔒 **${f.secretInfo.contentSecrets.length} potential secret(s) detected in file content.** Content intentionally not embedded.`
        );
      }
      sections.push("");
      continue;
    }

    if (f.isBinary) {
      sections.push("");
      sections.push("> Binary file — content not embedded.");
      sections.push("");
      continue;
    }

    if (f.content !== null && f.content !== undefined) {
      const ext = f.path.split('.').pop() || '';
      sections.push("");
      sections.push(`\`\`\`${ext}`);
      sections.push(f.content.trimEnd());
      sections.push("```");
    } else {
      sections.push("");
      sections.push("> Content not embedded (file exceeds size limit or is unreadable).");
    }
    sections.push("");
  }

  // Errors
  if (scanResult.errors && scanResult.errors.length > 0) {
    sections.push("## Errors");
    sections.push("");
    for (const err of scanResult.errors) {
      sections.push(`- ${err}`);
    }
    sections.push("");
  }

  sections.push("---");
  sections.push(`*Generated by Project Snapshot v${VERSION}*`);

  return sections.join("\n");
}

export function formatBytes(bytes: number): string {
  if (bytes === 0) return "0 B";
  const units = ["B", "KB", "MB", "GB", "TB"];
  let size = bytes;
  for (let i = 0; i < units.length; i++) {
    if (size < 1024 || i === units.length - 1) {
      return i === 0 ? `${size} B` : `${size.toFixed(1)} ${units[i]}`;
    }
    size /= 1024;
  }
  return `${size.toFixed(1)} PB`;
}
