"""Default constants for Project Snapshot."""

VERSION = "1.0.0"

DEFAULT_EXCLUDED_DIRS = {
    ".git",
    "node_modules",
    ".next",
    ".nuxt",
    "dist",
    "build",
    "coverage",
    ".venv",
    "venv",
    "__pycache__",
    ".cache",
    ".idea",
    ".vscode",
    ".tox",
    ".mypy_cache",
    ".pytest_cache",
    "eggs",
    ".eggs",
    "tmp",
    ".tmp",
}

DEFAULT_OUTPUT = "README.md"
DEFAULT_MANIFEST = "PROJECT-SNAPSHOT.json"

TEXT_EXTENSIONS = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs",
    ".json", ".jsonl", ".json5",
    ".yaml", ".yml",
    ".toml",
    ".xml", ".html", ".htm", ".xhtml",
    ".css", ".scss", ".sass", ".less",
    ".md", ".mdx", ".rst", ".txt",
    ".sql",
    ".sh", ".bash", ".zsh", ".fish",
    ".ps1", ".psm1", ".psd1",
    ".bat", ".cmd",
    ".rs", ".go", ".java", ".kt", ".kts",
    ".c", ".h", ".cpp", ".hpp", ".cxx", ".cc",
    ".cs",
    ".php",
    ".rb",
    ".vue", ".svelte",
    ".lua",
    ".dart",
    ".swift",
    ".r", ".R",
    ".pl", ".pm",
    ".tcl",
    ".ini", ".cfg", ".conf",
    ".env", ".env.local", ".env.production",
    ".dockerfile", ".dockerignore",
    ".gitignore", ".gitattributes",
    ".editorconfig",
    ".prettierrc", ".eslintrc",
    ".babelrc",
    "Makefile", "Dockerfile", "Jenkinsfile",
    "CMakeLists.txt",
    "setup.py", "setup.cfg", "pyproject.toml",
    "Gemfile", "Rakefile",
    "Gruntfile.js", "gulpfile.js",
    "webpack.config.js", "vite.config.js", "rollup.config.js",
}

BINARY_EXTENSIONS = {
    ".png", ".jpg", ".jpeg", ".gif", ".bmp", ".ico", ".svg", ".webp",
    ".mp3", ".mp4", ".avi", ".mov", ".wmv", ".flv", ".webm", ".mkv",
    ".wav", ".flac", ".aac", ".ogg", ".wma",
    ".zip", ".tar", ".gz", ".bz2", ".xz", ".7z", ".rar",
    ".exe", ".dll", ".so", ".dylib", ".bin",
    ".ttf", ".otf", ".woff", ".woff2", ".eot",
    ".sqlite", ".db", ".sqlite3",
    ".pdf", ".doc", ".docx", ".xls", ".xlsx", ".ppt", ".pptx",
    ".pyc", ".pyo", ".class",
    ".o", ".obj", ".lib", ".a",
    ".iso", ".img", ".dmg",
}

LANGUAGE_MAP = {
    ".py": "Python",
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".jsx": "React JavaScript",
    ".ts": "TypeScript",
    ".tsx": "React TypeScript",
    ".java": "Java",
    ".c": "C",
    ".h": "C Header",
    ".cpp": "C++",
    ".hpp": "C++ Header",
    ".cxx": "C++",
    ".cc": "C++",
    ".cs": "C#",
    ".go": "Go",
    ".rs": "Rust",
    ".rb": "Ruby",
    ".php": "PHP",
    ".swift": "Swift",
    ".kt": "Kotlin",
    ".kts": "Kotlin Script",
    ".dart": "Dart",
    ".lua": "Lua",
    ".sh": "Shell",
    ".bash": "Bash",
    ".zsh": "Zsh",
    ".fish": "Fish",
    ".ps1": "PowerShell",
    ".psm1": "PowerShell Module",
    ".bat": "Batch",
    ".cmd": "Batch",
    ".html": "HTML",
    ".htm": "HTML",
    ".xhtml": "XHTML",
    ".css": "CSS",
    ".scss": "SCSS",
    ".sass": "Sass",
    ".less": "Less",
    ".vue": "Vue",
    ".svelte": "Svelte",
    ".json": "JSON",
    ".jsonl": "JSON Lines",
    ".yaml": "YAML",
    ".yml": "YAML",
    ".toml": "TOML",
    ".xml": "XML",
    ".sql": "SQL",
    ".md": "Markdown",
    ".mdx": "MDX",
    ".rst": "reStructuredText",
    ".txt": "Text",
    ".r": "R",
    ".R": "R",
    ".pl": "Perl",
    ".pm": "Perl Module",
    ".tcl": "Tcl",
    ".ini": "INI",
    ".cfg": "Config",
    ".conf": "Config",
    ".dockerfile": "Dockerfile",
    ".dockerignore": "Docker Ignore",
    ".gitignore": "Git Ignore",
    ".gitattributes": "Git Attributes",
    ".editorconfig": "EditorConfig",
}

SECRET_PATTERNS = [
    r"-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----",
    r"ghp_[A-Za-z0-9]{36}",
    r"github_pat_[A-Za-z0-9_]{82}",
    r"AKIA[0-9A-Z]{16}",
    r"AIza[0-9A-Za-z\-_]{35}",
    r"sk-[A-Za-z0-9]{48}",
    r"sk_live_[A-Za-z0-9]{24,}",
    r"pk_live_[A-Za-z0-9]{24,}",
    r"SQ0csp-[A-Za-z0-9\-_]{43}",
    r"xox[baprs]-[A-Za-z0-9\-]+",
    r"(?i)password\s*[:=]\s*['\"].+['\"]",
    r"(?i)secret\s*[:=]\s*['\"].+['\"]",
    r"(?i)api[_-]?key\s*[:=]\s*['\"].+['\"]",
    r"(?i)access[_-]?token\s*[:=]\s*['\"].+['\"]",
]

SECRET_FILENAMES = {
    ".env",
    ".env.local",
    ".env.development",
    ".env.production",
    ".env.staging",
    ".env.test",
    "credentials.json",
    "service-account.json",
    "serviceAccountKey.json",
    ".npmrc",
    ".pypirc",
    ".netrc",
    ".htpasswd",
    "id_rsa",
    "id_ed25519",
    "id_dsa",
    "id_ecdsa",
    "*.pem",
    "*.key",
    "*.p12",
    "*.pfx",
}
