"""Output generation for Project Snapshot — Markdown and JSON."""

import json
import platform
import sys
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Optional

from .constants import VERSION, DEFAULT_EXCLUDED_DIRS
from .tree import generate_tree


def _format_json_manifest(
    scan_result: dict,
    project_root: Path,
    git_info: dict,
) -> dict:
    """Build the structured JSON manifest."""
    now = datetime.now(timezone.utc).isoformat()

    return {
        "tool": {
            "name": "project-snapshot",
            "version": VERSION,
        },
        "timestamp": now,
        "environment": {
            "python_version": sys.version,
            "platform": platform.platform(),
            "architecture": platform.machine(),
            "os": platform.system(),
            "hostname": platform.node(),
        },
        "project": {
            "root": str(project_root),
            "name": project_root.name,
        },
        "git": git_info,
        "statistics": scan_result["stats"],
        "files": [
            {k: v for k, v in f.items() if k != "content"}
            for f in scan_result["files"]
        ],
        "errors": scan_result.get("errors", []),
    }


def _format_markdown(
    scan_result: dict,
    project_root: Path,
    git_info: dict,
    excluded_dirs: set[str],
    include_default_heavy: bool,
) -> str:
    """Generate the Markdown snapshot."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    stats = scan_result["stats"]
    files = scan_result["files"]

    sections = []

    # Header
    sections.append(f"# Project Snapshot: `{project_root.name}`")
    sections.append("")
    sections.append(f"> Generated by **Project Snapshot v{VERSION}** on {now}")
    sections.append("")

    # Environment
    sections.append("## Environment")
    sections.append("")
    sections.append(f"- **OS:** {platform.platform()}")
    sections.append(f"- **Python:** {sys.version.split()[0]}")
    sections.append(f"- **Architecture:** {platform.machine()}")
    sections.append("")

    # Git
    if git_info.get("is_repository"):
        sections.append("## Git Information")
        sections.append("")
        sections.append(f"- **Repository:** Yes")
        sections.append(f"- **Branch:** `{git_info.get('branch', 'unknown')}`")
        sections.append(f"- **Commit:** `{git_info.get('short_commit', 'unknown')}`")
        if git_info.get("origin"):
            sections.append(f"- **Origin:** `{git_info['origin']}`")
        if git_info.get("modified_files"):
            sections.append(f"- **Modified files:** {len(git_info['modified_files'])}")
        if git_info.get("untracked_files"):
            sections.append(f"- **Untracked files:** {len(git_info['untracked_files'])}")
        sections.append("")
    else:
        sections.append("## Git Information")
        sections.append("")
        sections.append("- **Repository:** No (not a Git repository)")
        sections.append("")

    # Excluded directories
    if not include_default_heavy:
        sections.append("## Excluded Directories")
        sections.append("")
        sections.append(
            "The following directories are excluded by default to avoid scanning "
            "generated/dependency content. Use `--include-default-heavy` to include them."
        )
        sections.append("")
        for d in sorted(DEFAULT_EXCLUDED_DIRS):
            sections.append(f"- `{d}`")
        sections.append("")

    # Statistics
    sections.append("## Project Statistics")
    sections.append("")
    sections.append(f"| Metric | Value |")
    sections.append(f"|--------|-------|")
    sections.append(f"| Total files | {stats['total_files']} |")
    sections.append(f"| Total directories | {stats['total_directories']} |")
    sections.append(f"| Total size | {stats['total_size_human']} |")
    sections.append(f"| Text files | {stats['text_files']} |")
    sections.append(f"| Binary files | {stats['binary_files']} |")
    sections.append(f"| Symlinks | {stats['symlinks']} |")
    sections.append(f"| Secret detections | {stats['secret_detections']} |")
    sections.append("")

    # Languages
    if stats["languages"]:
        sections.append("## Languages")
        sections.append("")
        sections.append("| Language | Files |")
        sections.append("|----------|-------|")
        for lang, count in stats["languages"].items():
            sections.append(f"| {lang} | {count} |")
        sections.append("")

    # Extensions
    if stats["extensions"]:
        sections.append("## File Extensions")
        sections.append("")
        sections.append("| Extension | Count |")
        sections.append("|-----------|-------|")
        for ext, count in stats["extensions"].items():
            sections.append(f"| `{ext}` | {count} |")
        sections.append("")

    # Tree
    tree_str = generate_tree(project_root, excluded_dirs if not include_default_heavy else set())
    sections.append("## Project Tree")
    sections.append("")
    sections.append("```text")
    sections.append(tree_str)
    sections.append("```")
    sections.append("")

    # Largest files
    if stats["largest_files"]:
        sections.append("## Largest Files")
        sections.append("")
        sections.append("| Size | Path |")
        sections.append("|------|------|")
        for lf in stats["largest_files"][:15]:
            from .scanner import _human_readable_size
            size_str = _human_readable_size(lf["size"])
            sections.append(f"| {size_str} | `{lf['path']}` |")
        sections.append("")

    # File contents
    sections.append("## File Contents")
    sections.append("")

    for f in files:
        if f["is_directory"]:
            continue

        rel = f["path"]
        sections.append(f"### `{rel}`")
        sections.append("")

        if f["is_symlink"]:
            sections.append(f"- **Type:** Symlink")
            sections.append(f"- **Target:** `{f.get('symlink_target', 'unknown')}`")
            sections.append("")
            continue

        sections.append(f"- **Size:** {f['size_human']}")
        sections.append(f"- **SHA-256:** `{f['sha256']}`")
        if f["modified"]:
            sections.append(f"- **Modified:** {f['modified']}")
        if f["permissions"]:
            sections.append(f"- **Permissions:** {f['permissions']}")
        if f["language"] and f["language"] != "Unknown":
            sections.append(f"- **Language:** {f['language']}")
        if f["mime_type"]:
            sections.append(f"- **MIME:** {f['mime_type']}")

        secret_info = f.get("secret_info", {})
        if secret_info.get("has_secrets"):
            if secret_info.get("is_secret_file"):
                sections.append("")
                sections.append("> \U0001f512 **Potential secret detected.** Content intentionally not embedded.")
                sections.append(">")
                sections.append("> This file appears to contain sensitive information (e.g., API keys, credentials, private keys).")
                sections.append("> Only metadata is included in this snapshot for security reasons.")
            elif secret_info.get("content_secrets"):
                sections.append("")
                sections.append(
                    f"> \U0001f512 **{len(secret_info['content_secrets'])} potential secret(s) detected in file content.** "
                    "Content intentionally not embedded."
                )
            sections.append("")
            continue

        if f["is_binary"]:
            sections.append("")
            sections.append("> Binary file — content not embedded.")
            sections.append("")
            continue

        content = f.get("content")
        if content is not None:
            suffix = Path(rel).suffix.lstrip(".")
            lang_tag = suffix if suffix else ""
            sections.append("")
            sections.append(f"```{lang_tag}")
            sections.append(content.rstrip())
            sections.append("```")
        else:
            sections.append("")
            sections.append("> Content not embedded (file exceeds size limit or is unreadable).")

        sections.append("")

    # Errors
    errors = scan_result.get("errors", [])
    if errors:
        sections.append("## Errors")
        sections.append("")
        for err in errors:
            sections.append(f"- {err}")
        sections.append("")

    sections.append("---")
    sections.append(f"*Generated by Project Snapshot v{VERSION}*")

    return "\n".join(sections)


def write_output(
    scan_result: dict,
    project_root: Path,
    git_info: dict,
    excluded_dirs: set[str],
    include_default_heavy: bool,
    output_path: str,
    manifest_path: str,
) -> None:
    """Write both Markdown and JSON output files."""
    md_content = _format_markdown(
        scan_result, project_root, git_info, excluded_dirs, include_default_heavy,
    )
    json_content = _format_json_manifest(scan_result, project_root, git_info)

    out_file = Path(output_path)
    out_file.parent.mkdir(parents=True, exist_ok=True)
    out_file.write_text(md_content, encoding="utf-8")
    print(f"Markdown snapshot written to: {out_file}")

    manifest_file = Path(manifest_path)
    manifest_file.parent.mkdir(parents=True, exist_ok=True)
    manifest_file.write_text(
        json.dumps(json_content, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"JSON manifest written to: {manifest_file}")
